---
title: "Visual Analytics - Project Data Preparation"
author: "J. Hamski"
date: "May 3, 2016"
output: html_document
---



#### Packages 
```{r}
library(readxl)
library(readr)
library(dplyr)
library(ggplot2)
library(zoo)
```

#### Load Microdata Excel File
```{r}
microdata.original <- read_excel('FRBNY-SCE-Public-Microdata-Complete.xlsx', sheet = 'Data', na = "NA", skip = 1)
```

```{r}
microdata.original <- microdata.original[,-189] 

microdata <- select(microdata.original, -QNUM1, -QNUM2, -QNUM3, -QNUM5, -QNUM6, -Q9_bin1, -Q9_bin2, -Q9_bin3, -Q9_bin4, -Q9_bin5, -Q9_bin6, -Q9_bin7, -Q9_bin8, -Q9_bin9, -Q9_bin10, -Q9c_bin1, -Q9c_bin2, -Q9c_bin3, -Q9c_bin4, -Q9c_bin5, -Q9c_bin6, -Q9c_bin7, -Q9c_bin8, -Q9c_bin9, -Q9c_bin10)

```


#### Cleaning the microdata dataframe
```{r}
fields <- read_excel("microdata fields.xlsx", sheet = "ColumnKey")
fields <- fields[,1:2]

removal.list <- c("QNUM1", "QNUM2", "QNUM3", "QNUM5", "QNUM6", "Q9_bin1", "Q9_bin2", "Q9_bin3", "Q9_bin4", "Q9_bin5", "Q9_bin6", "Q9_bin7", "Q9_bin8", "Q9_bin9", "Q9_bin10", "Q9c_bin1", "Q9c_bin2", "Q9c_bin3", "Q9c_bin4", "Q9c_bin5", "Q9c_bin6", "Q9c_bin7", "Q9c_bin8", "Q9c_bin9", "Q9c_bin10")

fields <- fields %>%
  filter(!ID %in% removal.list)

colnames(microdata) <- fields$Description
```

```{r}
microdata.original$date <- as.character(microdata.original$date)
microdata$`Month Survey was administered` <- as.Date(as.yearmon(microdata.original$date, "%Y%m"), frac = 1)
```

#### Column-spectific changes 

```{r}
better.worse <- c("much worse off",
                 "somewhat worse off",
                 "about the same",
                 "somewhat better off",
                 "much better off")

microdata$`Financially better or worse off than 12 months ago` <- factor(microdata$`Financially better or worse off than 12 months ago`, levels = 1:5, labels = better.worse)
microdata$`Financially better or worse off 12 months from now` <- factor(microdata$`Financially better or worse off 12 months from now`, levels = 1:5, labels = better.worse)
```

```{r}
harder.easier <- c("much harder",
                 "somewhat harder",
                 "Equally hard/easy",
                 "somewhat easier",
                 "much easier")

microdata$`Harder or easier to obtain credit compared to 12 months ago` <- factor(microdata$`Harder or easier to obtain credit compared to 12 months ago`, levels = 1:5, labels = harder.easier)
microdata$`Harder or easier to obtain credit compared to 12 months from now` <- factor(microdata$`Harder or easier to obtain credit compared to 12 months from now`, levels = 1:5, labels = harder.easier)
```

#### Demographic Sections
```{r}
gender <- c("female", "male")
no.yes <- c("no", "yes")

microdata$Gender <- factor(microdata$Gender, levels = 1:2, labels = gender)

microdata$`Hispanic, Latino, or Spanish Origin` <- factor(microdata$`Hispanic, Latino, or Spanish Origin`, levels = 1:2, labels = no.yes)
microdata$`Identify as white` <- factor(microdata$`Identify as white`, levels = 0:1, labels = no.yes)
microdata$`Identify as black/African American` <- factor(microdata$`Identify as black/African American`, levels = 0:1, labels = no.yes)
microdata$`Identify as American Indian / Alaska Native` <- factor(microdata$`Identify as American Indian / Alaska Native`, levels = 0:1, labels = no.yes)
microdata$`Identify as Asian` <- factor(microdata$`Identify as Asian`, levels = 0:1, labels = no.yes)
microdata$`Identify as Native Hawaiian or other Pacific Islander` <- factor(microdata$`Identify as Native Hawaiian or other Pacific Islander`, levels = 0:1, labels = no.yes)
microdata$`Identify as other race` <- factor(microdata$`Identify as other race`, levels = 0:1, labels = no.yes)
```

```{r}
education.levels <- c("Less than high school",
                      "High school dipoma/equivalent",
                      "Some college but no degree",
                      "Associates/ JC College degree",
                      "Bachelor's Degree",
                      "Master's Degree",
                      "Doctoral Degree",
                      "Professional Degree",
                      "Other education")

microdata$`Highest level of education completed` <- factor(microdata$`Highest level of education completed`, levels = 1:9, labels = education.levels)
```

```{r}
length <- c("Less than 1 month",
            "Between 1 and 6 months",
            "Between 6 months and 1 year",
            "Between 1 year and 5 years",
            "More than 5 years")

yes.no <- c("yes", "no")

microdata$`Length of employment at current job` <- factor(microdata$`Length of employment at current job`, levels = 1:5, labels = length)

microdata$`Are you currently married or living as a partner with someone` <- factor(microdata$`Are you currently married or living as a partner with someone`, levels = 0:1, labels = yes.no)
```


```{r}
own.rent <- c("own", "rent", "other")

microdata$`Own or Rent primary Residence` <- factor(microdata$`Own or Rent primary Residence`, levels = 1:3, labels = own.rent)
microdata$`Own other homes` <- factor(microdata$`Own other homes`, levels = 1:2, labels = yes.no)
microdata$`Live alone` <- factor(microdata$`Live alone`, levels = 0:1, labels = no.yes)
```

```{r}
incomes <- c( "Less than $10,000",
              "$10,000 to $19,999",
              "$20,000 to $29,999",
              "$30,000 to $39,999",
              "$40,000 to $49,999",
              "$50,000 to $59,999",
              "$60,000 to $74,999",
              "$75,000 to $99,999",
              "$100,000 to $149,999",
              "$150,000 to $199,999",
              "$200,000 or more")

microdata$`Total combined pretax income in household` <- factor(microdata$`Total combined pretax income in household`, levels = 1:length(incomes), labels = incomes)
```


```{r}
save(microdata, file = "ConsumerExpectationsExplorer/survey_microdata.Rda")
```

```{r}

```

